### ISSUE TITLE
typo in Serial Example

### ISSUE THREAD

**Issue by the-programmer** [ARMmbed/mbed_OS_API_Docs#64]
In the Serial documentation under example three there is a typo in the [example code](https://github.com/ARMmbed/mbed_OS_API_Docs/blob/master/docs/APIs/interfaces/digital/Serial.md#example-three).
`pc.attach(&callback;);`
There is a ; to much after the callback statement.

**Comment by iriark01** [comment]
@AnotherButler can you confirm, please?

**Comment by AnotherButler** [comment]
Confirmed; the actual code from the program is `pc.attach(&callback_ex);`

@mbartling This is changing from a snippet to a project, so this should fix itself, right?

**Comment by AnotherButler** [comment]
We [have resolved](https://docs.mbed.com/docs/mbed-os-api-reference/en/latest/APIs/interfaces/digital/Serial/) this issue by having a project generate the text, so it should no longer be out of date. @the-programmer, can we close this issue?

**Comment by the-programmer** [comment]
@AnotherButler Looks good on the official page. However there now is a mismatch between the github code and the official page. But I assume that will be fixed in time.

**Comment by mbartling** [comment]
It should already be fixed? 
https://developer.mbed.org/teams/mbed_example/code/Serial_ex_3/file/3b040f367dd8/main.cpp

**Comment by the-programmer** [comment]
Ok,

Looks good now. Time to close this issue.
