### ISSUE TITLE
Callback page, missing template parameters

### ISSUE THREAD

**Issue by janjongboom** [ARMmbed/mbed_OS_API_Docs#89]
```
First, you need to understand the syntax of the Callback type. The Callback type is a templated type parameterized by a C++ function declaration:

// Callback cb;
Callback cb;          // A callback that takes in a float and returns an int
Callback cb;         // A callback that takes in a float and returns nothing
Callback cb;               // A callback that takes in nothing and returns an int
Callback cb;  // A callback that takes in two floats and returns nothing
```

All Callback objects look the same, but they should have template arguments.

**Comment by AnotherButler** [comment]
@geky Can you please address this?

**Comment by geky** [comment]
Uhhhh, that's strange:
https://github.com/ARMmbed/Handbook/blob/new_engine/docs/reference/api/platform/platform.md#create-callbacks

@micque01, I was told to cc you, it looks like the online site is picking up the templates as html tags even though it's in a code block?

**Comment by micque01** [comment]
Ah yeah, definitely a defect in the markdown conversion in the docs engine, not a problem with the docs themselves. I'll raise a defect in JIRA and get this fixed ASAP. Thanks!

**Comment by AnotherButler** [comment]
Thanks, @micque01 Is this ready to close, or is it still a WIP?

**Comment by geky** [comment]
Seems fixed 👍 

(although there's no syntax highlighting :( )

**Comment by micque01** [comment]
Yep, should be fixed. We need to implement a new syntax highlighter because the one we had was awful, so we will have syntax highlighting at some point :)

**Comment by AnotherButler** [comment]
Awesome. Thanks :)
