### ISSUE TITLE
Remove word-break: break-all from code blocks

### ISSUE THREAD

**Issue by janjongboom** [ARMmbed/mbed_OS_API_Docs#90]
Now the wrapping is really weird for `<code>` blocks.

**Comment by AnotherButler** [comment]
@janjongboom Could you please be more specific with the problem and location?

**Comment by janjongboom** [comment]
<img width="753" alt="screen shot 2017-10-01 at 12 20 45" src="https://user-images.githubusercontent.com/816856/31053653-a5cf7204-a6a2-11e7-8455-972da6e2dada.png">

`NSAPI_ERROR_WOULD_BLOCK` is a `<code>` block. Currently it has `word-break: break-all` in its CSS, and this causes the rendering to just break per letter. This looks weird. It should not do this.

@AnotherButler

**Comment by AnotherButler** [comment]
@micque01 Is this something you need to fix?

**Comment by micque01** [comment]
@AnotherButler Yes this is something I can fix

**Comment by AnotherButler** [comment]
@micque01 Can I close this issue, or should I first create this as a JIRA task for y'all?

**Comment by micque01** [comment]
There is a JIRA issue for this here in the docs epic https://jira.arm.com/browse/IOTWEB-3074, so it is on our radar to fix

**Comment by AnotherButler** [comment]
Thanks so much. I'm going to close this, and we can follow it in JIRA.
